# Generated by Django 3.0.3 on 2020-02-15 03:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_book_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hero',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
