# Generated by Django 3.0.3 on 2020-02-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sumary',
            field=models.TextField(verbose_name='正文'),
        ),
    ]
