# Generated by Django 3.0.3 on 2020-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_auto_20200215_1531'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hero',
            managers=[
            ],
        ),
    ]
